version: '3.9'

services:
  postgres:
    image: postgres:16-alpine
    ports:
      - 5432:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=PM_password
      - POSTGRES_USER=PM_user
      - POSTGRES_DB=pm_assignment

  fastapi-server:
    ports:
      - 80:80
    build: .
    container_name: fastapi-server
    depends_on:
      - postgres