version: '3.9'

services:
  postgres-dev:
    image: postgres:16-alpine
    ports:
      - 5432:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=PM_password
      - POSTGRES_USER=PM_user
      - POSTGRES_DB=pm_assignment

  fastapi-server:
    ports:
      - 80:80
    build: .
    container_name: fastapi-server
    depends_on:
      - postgres-dev
    environment:
      - POSTGRES_DB_PASSWORD=PM_password
      - POSTGRES_DB_USER=PM_user
      - POSTGRES_DB_NAME=pm_assignment
      - POSTGRES_DB_HOST=postgres-dev

  intg-api-tests:
    build:
      dockerfile: Dockerfile-intg-api-test
    container_name: intg-api-tests
    depends_on:
      - postgres-dev
    environment:
      - POSTGRES_DB_PASSWORD=PM_password
      - POSTGRES_DB_USER=PM_user
      - POSTGRES_DB_NAME=pm_assignment
      - POSTGRES_DB_HOST=postgres-dev
